create table if not exists public.applications (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  company text not null,
  role text not null,
  status text not null default 'Applied',
  applied_date text,
  next_step text,
  priority text not null default 'Medium',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.applications enable row level security;

do $$
begin
  if not exists (
    select 1
    from pg_indexes
    where schemaname = 'public'
      and indexname = 'applications_user_id_created_at_idx'
  ) then
    create index applications_user_id_created_at_idx
      on public.applications (user_id, created_at desc);
  end if;

  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'applications'
      and policyname = 'Users can read their own applications'
  ) then
    create policy "Users can read their own applications" on public.applications
      for select using (auth.uid() = user_id);
  end if;

  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'applications'
      and policyname = 'Users can insert their own applications'
  ) then
    create policy "Users can insert their own applications" on public.applications
      for insert with check (auth.uid() = user_id);
  end if;

  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'applications'
      and policyname = 'Users can update their own applications'
  ) then
    create policy "Users can update their own applications" on public.applications
      for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
  end if;

  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'applications'
      and policyname = 'Users can delete their own applications'
  ) then
    create policy "Users can delete their own applications" on public.applications
      for delete using (auth.uid() = user_id);
  end if;
end $$;
