create table if not exists public.applications (
  id bigint generated by default as identity primary key,
  company text not null,
  role text not null,
  status text not null default 'Applied',
  applied_date text,
  next_step text,
  priority text not null default 'Medium',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.applications enable row level security;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'applications'
      and policyname = 'Allow read access'
  ) then
    create policy "Allow read access" on public.applications
      for select using (true);
  end if;

  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'applications'
      and policyname = 'Allow insert access'
  ) then
    create policy "Allow insert access" on public.applications
      for insert with check (true);
  end if;

  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'applications'
      and policyname = 'Allow update access'
  ) then
    create policy "Allow update access" on public.applications
      for update using (true) with check (true);
  end if;

  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'applications'
      and policyname = 'Allow delete access'
  ) then
    create policy "Allow delete access" on public.applications
      for delete using (true);
  end if;
end $$;
